name: "Get Commit"
description: "Get Full Commit Details for Push and Pull Requests including the Head Commit."
author: "Shane"

branding:
  icon: "git-pull-request"
  color: "red"

inputs:
  sha:
    description: "Specify the SHA of the Commit"
  path:
    description: "Object Selector"
  selector:
    description: "Object Selector"
    deprecationMessage: "Input changed too: path"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  sha:
    description: "Commit SHA"
  commit:
    description: "Full Commit JSON"
  result:
    description: "Result from Path"
  message:
    description: "Commit Message"
  html_url:
    description: "HTML URL"
  comment_count:
    description: "Comment Count"
  author:
    description: "Commit Author (Parsed)"

runs:
  using: "node24"
  main: "dist/index.js"
